# Generated by Django 4.0.4 on 2022-04-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octopgpyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='app',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='octopgpyapp.app'),
            preserve_default=False,
        ),
    ]
