# Generated by Django 4.0.4 on 2022-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopgpyapp', '0002_app_document_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='test',
        ),
        migrations.AlterField(
            model_name='field',
            name='calculation_func',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='calculation_func_args',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_calculated',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
