# Generated by Django 4.0.4 on 2022-04-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopgpyapp', '0005_alter_field_is_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='calculation_func',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='calculation_func_args',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
