# Generated by Django 4.0.6 on 2022-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopgpyapp', '0007_alter_field_name_alter_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('numeric', 'numeric'), ('timestamp', 'timestamp')], default='text', max_length=30, null=True),
        ),
    ]
