# Generated by Django 4.0.6 on 2022-07-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopgpyapp', '0012_cte_ctefields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CTEFields',
            new_name='DocumentView',
        ),
    ]
