# Generated by Django 4.0.6 on 2022-07-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octopgpyapp', '0013_rename_ctefields_documentview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('agg', models.CharField(choices=[('sum', 'sum'), ('avg', 'avg')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentview',
            name='agg',
        ),
        migrations.RemoveField(
            model_name='documentview',
            name='cte',
        ),
        migrations.AddField(
            model_name='documentview',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='octopgpyapp.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentview',
            name='parent_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_sub_child', to='octopgpyapp.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentview',
            name='parent_documentview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='octopgpyapp.documentview'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CTE',
        ),
        migrations.AddField(
            model_name='fromdocument',
            name='dw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopgpyapp.documentview'),
        ),
    ]
