# Generated by Django 4.0.6 on 2022-11-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopgpyapp', '0014_fromdocument_remove_documentview_agg_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FromDocument',
            new_name='FromClause',
        ),
    ]
